### ISSUE TITLE
Doesn't work with `CARGO_INCREMENTAL`.

### ISSUE THREAD

**Issue by dpc** [japaric/cortex-m#32]
It took me a long while to debug why linker script behaves erratically and sometimes compiles right, but other times complaints either about the lack of exception handlers or too many of them if I attempt to add them. Turns out, all it took is to disable `CARGO_INCREMENTAL` environment variable.

**Comment by japaric** [comment]
You should report this in rust-lang/rust if it's not there already. AFAIR there was an issue open about incremental compilation having problems with lang items / linker_section and resulting in linker errors. You should check if that's the same error you have been running into, and if not you should open a new issue.

**Comment by japaric** [comment]
Added a warning about this to the how to use and the troubleshooting sections of the cortex-m-quickstart [documentation](https://docs.rs/cortex-m-quickstart/0.1.5/cortex_m_quickstart/#used-cargo_incremental1).

**Comment by japaric** [comment]
Oh, and I *think* the cause the problem is that incr. comp. is ignoring `#[linker_section]` directives but I haven't had a chance to investigate that just yet.

**Comment by dpc** [comment]
I think that would fit my symptoms, yes.
