### ISSUE TITLE
HardFault in Primask::read

### ISSUE THREAD

**Issue by xd009642** [japaric/cortex-m#93]
I've been working on making an embedded-hal implementation for the stm32f469 and building up to a board specific crate for the  stm32f469i discovery board and have got to the point where I've started trying to flash some LEDs but I encountered a hard fault when executing `Primask::read`

Here is the project I'm programming onto the board [link](https://github.com/xd009642/stm32f469i-disco/blob/leds/examples/leds_on.rs) and below is some output from gdb from when I was stepping through. The fault's probably my own so any help would be appreciated!

```
Breakpoint 1, leds_on::main::hfa770daafd2bee96 () at examples/leds_on.rs:30
30	    let p = stm32f469xx::Peripherals::take().unwrap();
>>> step
stm32f469xx::Peripherals::take::h6b0a9d4241464a77 ()
    at /home/xd009642/.cargo/registry/src/github.com-1ecc6299db9ec823/stm32f469xx-0.2.1/src/lib.rs:473549
473549	        cortex_m::interrupt::free(|_| {
>>> step
cortex_m::interrupt::free::he28aea6b14b68ad8 (f=...)
    at /home/xd009642/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.5.2/src/interrupt.rs:64
64	    let primask = ::register::primask::read();
>>> step
cortex_m::register::primask::read::h1846bf7d2763250f ()
    at /home/xd009642/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.5.2/src/register/primask.rs:44
44	                    unsafe { __primask() }
>>> step
HardFault () at asm.s:4
4	  mrs r0, MSP
>>> step
5	  bl UserHardFault
>>> step
UserHardFault (ef=0x2004fef0) at <exception macros>:10
10	<exception macros>: No such file or directory.
>>> step
leds_on::safe_state::hd0df1968d7543a7e (_ef=0x2004fef0) at examples/leds_on.rs:26
26	    loop {}
>>> step
```

EDIT: Done some peeking and poking of the ARM fault status registers and this hard fault is down to an undefined instruction. These appear to be at the end of the panics but it doesn't appear to hit a panic.

**Comment by xd009642** [comment]
Bump. This is still an issue, any help or guidance would be appreciated!

**Comment by japaric** [comment]
Are you using LLD to link your program? There's a [bug](https://bugs.llvm.org/show_bug.cgi?id=38435) that makes LLD emit invalid instructions in the output binary. Switch to GNU LD or GCC for the time being.

**Comment by xd009642** [comment]
I was and thank you, that solved it :+1:

**Comment by norbux** [comment]
I seem to have this same problem, could you give me a hint about how to switch from LLD to GNU LD or GCC as recommended by @japaric ?

**Comment by xd009642** [comment]
@norbux so I have a `.cargo/config` file with the following contents:

```
[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = 'arm-none-eabi-gdb'
rustflags = [
    "-C", "link-arg=-Wl,-Tlink.x",
    "-C", "link-arg=-nostartfiles"
]
```

Before when I had that issue there was another rustflag `"-C", "link-arg=-fuse-ld=lld",` which I got from one of the rust embedded tutorials or example projects.

**Comment by norbux** [comment]
@xd009642 Thanks! I fixed the problem, it wasn't the linker settings in my case, it was just that the dependencies versions were very old for my environment, Now it works fine
